# Example file

version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
  redis:
    image: "redis:latest"
